steps:
  - name: gcr.io/cloud-builders/git
    args: [ 'clone', 'https://github.com/vjroby/ggi-github-insights' ]
    id: 'check-out-source-code'
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ 'set_env.sh' ]
    dir: '$REPO_NAME/build-pipeline'
    id: 'set_up_env_vars'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get install -y zip
        sh package.sh
    dir: '$REPO_NAME/build-pipeline'
    id: 'packaging_zip_archive'
  - name: gcr.io/cloud-builders/gsutil
    args: [ 'cp', 'package.zip', 'gs://${ARTIFACTS_BUCKET}/package_$BUILD_ID.zip' ]
    dir: '$REPO_NAME'
    id: 'deploy-package'